import "./globals.css";
import { TwinklingStars, NoRightClick } from './components';

export const metadata = {
  title: "Jessica Gallagher | Software Engineer",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body>
        <NoRightClick>
          <TwinklingStars>{children}</TwinklingStars>
        </NoRightClick>
      </body>
    </html>
  );
}
