import './globals.css';
import { TwinklingStars, NoRightClick } from './components';

export const metadata = {
  title: `Jessica Gallagher's Personal Portfolio`,
  name: `Jessica Gallagher | Software Engineer`,
  description:
    'Jessica Gallagher is a Brooklyn, New York-based full stack software engineer with a passion for creating user-friendly, engaging, and intuitive experiences using Next.js, Tailwind CSS, Supabase, and Prismic CMS.',
  keywords: [
    'jessica gallagher',
    'jessica l gallagher',
    'jessica lyn gallagher',
    'full stack engineer',
    'full-stack engineer',
    'frontend engineer',
    'front end engineer',
    'front-end engineer',
    'software developer',
    'software engineer',
    'web developer',
    'website developer',
    'web designer',
    'website designer',
    'developer',
    'engineer',
    'software designer',
    'jessica gallagher nyc',
    'jessica l gallagher nyc',
    'jessica lyn gallagher nyc',
    'jessica gallagher new york city',
    'jessica l gallagher new york city',
    'jessica lyn gallagher new york city',
    'jessica gallagher brooklyn',
    'jessica l gallagher brooklyn',
    'jessica lyn gallagher brooklyn',
    'jessica gallagher brooklyn, ny',
    'jessica l gallagher brooklyn, ny',
    'jessica lyn gallagher brooklyn, ny',
    'jessica gallagher manhattan',
    'jessica l gallagher manhattan',
    'jessica lyn gallagher manhattan',
    'jessica gallagher brooklyn, new york',
    'jessica l gallagher brooklyn, new york',
    'jessica lyn gallagher brooklyn, new york',
    'nyc full stack engineer',
    'nyc full-stack engineer',
    'nyc frontend engineer',
    'nyc front end engineer',
    'nyc front-end engineer',
    'nyc software developer',
    'nyc software engineer',
    'nyc web developer',
    'nyc website developer',
    'nyc web designer',
    'nyc website designer',
    'nyc developer',
    'nyc engineer',
    'nyc software designer',
    'prismic',
    'new york city full stack engineer',
    'new york city full-stack engineer',
    'new york city frontend engineer',
    'new york city front end engineer',
    'new york city front-end engineer',
    'new york city software developer',
    'new york city software engineer',
    'new york city web developer',
    'new york city website developer',
    'new york city web designer',
    'new york city website designer',
    'new york city developer',
    'new york city  engineer',
    'new york city software designer',
    'prismic cms',
    'brooklyn full stack engineer',
    'brooklyn full-stack engineer',
    'brooklyn frontend engineer',
    'brooklyn front end engineer',
    'brooklyn front-end engineer',
    'brooklyn software developer',
    'brooklyn software engineer',
    'brooklyn web developer',
    'brooklyn website developer',
    'brooklyn web designer',
    'brooklyn website designer',
    'brooklyn developer',
    'brooklyn engineer',
    'brooklyn software designer',
    'tailwind',
    'brooklyn, ny full stack engineer',
    'brooklyn, ny full-stack engineer',
    'brooklyn, ny frontend engineer',
    'brooklyn, ny front end engineer',
    'brooklyn, ny front-end engineer',
    'brooklyn, ny software developer',
    'brooklyn, ny software engineer',
    'brooklyn, ny web developer',
    'brooklyn, ny website developer',
    'brooklyn, ny web designer',
    'brooklyn, ny website designer',
    'brooklyn, ny developer',
    'brooklyn, ny engineer',
    'brooklyn, ny software designer',
    'tailwind css',
    'brooklyn, new york full stack engineer',
    'brooklyn, new york full-stack engineer',
    'brooklyn, new york frontend engineer',
    'brooklyn, new york front end engineer',
    'brooklyn, new york front-end engineer',
    'brooklyn, new york software developer',
    'brooklyn, new york software engineer',
    'brooklyn, new york web developer',
    'brooklyn, new york website developer',
    'brooklyn, new york web designer',
    'brooklyn, new york website designer',
    'brooklyn, new york developer',
    'brooklyn, new york engineer',
    'brooklyn, new york software designer',
    'next.js',
    'manhattan full stack engineer',
    'manhattan full-stack engineer',
    'manhattan frontend engineer',
    'manhattan front end engineer',
    'manhattan front-end engineer',
    'manhattan software developer',
    'manhattan software engineer',
    'manhattan web developer',
    'manhattan website developer',
    'manhattan web designer',
    'manhattan website designer',
    'manhattan developer',
    'manhattan engineer',
    'manhattan software designer',
    'nextjs',
    'supabase',
    'html',
    'css',
    'javascript',
    'freelance',
    'freelancer',
    'vercel',
  ],
  authors: [
    { name: 'Jessica Gallagher', url: 'https://www.jessicagallagher.com' },
  ],
  creator: 'Jessica Gallagher',
  publisher: 'Jessica Gallagher',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className='font-lato'>
        {/* <NoRightClick> */}
        {children}
        {/* </NoRightClick> */}
      </body>
    </html>
  );
}
